{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secureyeoman.fullname" . }}-secrets
  namespace: {{ include "secureyeoman.namespace" . }}
  labels:
    {{- include "secureyeoman.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  {{- if .Values.secrets.githubOauthClientId }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.secrets.githubOauthClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.githubOauthClientSecret }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.secrets.githubOauthClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleOauthClientId }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.secrets.googleOauthClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleOauthClientSecret }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.secrets.googleOauthClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.gmailOauthClientId }}
  GMAIL_OAUTH_CLIENT_ID: {{ .Values.secrets.gmailOauthClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.gmailOauthClientSecret }}
  GMAIL_OAUTH_CLIENT_SECRET: {{ .Values.secrets.gmailOauthClientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
