{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "secureyeoman.fullname" . }}-core
  namespace: {{ include "secureyeoman.namespace" . }}
  labels:
    {{- include "secureyeoman.componentLabels" (dict "context" . "component" "core") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "secureyeoman.selectorLabels" (dict "context" . "component" "core") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}
